# Generated by Django 5.1.2 on 2024-10-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_column='fs_cargo_nome', max_length=150)),
            ],
            options={
                'db_table': 't_cargo',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_column='fs_filial_sigla', max_length=3)),
                ('nome', models.CharField(db_column='fs_filial_nome', max_length=150)),
            ],
            options={
                'db_table': 't_filiais',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_column='fs_role_nome', max_length=150)),
            ],
            options={
                'db_table': 't_roles',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_column='fs_setor_nome', max_length=150)),
            ],
            options={
                'db_table': 't_setor',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 't_solicitacao',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 't_solicitacao_tipo',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_column='fs_status_descricao', max_length=50)),
            ],
            options={
                'db_table': 't_status',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacaoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_tipo_operacao_frete',
            },
        ),
        migrations.CreateModel(
            name='TipoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_column='fs_tipo_senha_descricao', max_length=50)),
            ],
            options={
                'db_table': 't_tipo_senha',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao', models.CharField(db_column='fs_cotacao_id', max_length=20)),
                ('valor_nota', models.DecimalField(db_column='ff_valor_nota', decimal_places=2, max_digits=10)),
                ('peso_mercadoria', models.DecimalField(db_column='ff_peso_mercadoria', decimal_places=2, max_digits=10)),
                ('peso_cubado_mercadoria', models.DecimalField(db_column='ff_peso_cubado_mercadoria', decimal_places=2, max_digits=10)),
                ('valor_cotacao', models.DecimalField(db_column='ff_valor_cotacao', decimal_places=2, max_digits=10)),
                ('remetente', models.CharField(db_column='fs_remetente_id', max_length=18)),
                ('destinatario', models.CharField(db_column='fs_destinatario_id', max_length=18)),
                ('consignatario', models.CharField(db_column='fs_consignatario_id', max_length=18)),
                ('solicitacao', models.ForeignKey(db_column='fn_solicitacao_id', on_delete=django.db.models.deletion.RESTRICT, to='api.solicitacao')),
                ('tipo_operacao_frete', models.ForeignKey(db_column='fn_tipo_operacao_frete_id', on_delete=django.db.models.deletion.RESTRICT, to='api.tipooperacaofrete')),
                ('tipo_senha', models.ForeignKey(db_column='fn_tipo_senha_id', on_delete=django.db.models.deletion.RESTRICT, to='api.tiposenha')),
            ],
            options={
                'db_table': 't_solicitacao_senhas',
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_solicitacao',
            field=models.ForeignKey(db_column='fn_solicitacao_tipo_id', on_delete=django.db.models.deletion.RESTRICT, to='api.solicitacaotipo'),
        ),
        migrations.CreateModel(
            name='RegraAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro_1', models.CharField(db_column='fs_parametro_1', max_length=150)),
                ('parametro_2', models.CharField(db_column='fs_parametro_2', max_length=150)),
                ('parametro_3', models.CharField(db_column='fs_parametro_3', max_length=150)),
                ('parametro_4', models.CharField(db_column='fs_parametro_4', max_length=150)),
                ('parametro_5', models.CharField(db_column='fs_parametro_5', max_length=150)),
                ('nivel_aprovacao', models.IntegerField(db_column='fn_aprovacao_nivel')),
                ('cargo', models.ForeignKey(db_column='fn_cargo_id', on_delete=django.db.models.deletion.RESTRICT, to='api.cargo')),
                ('filial', models.ForeignKey(db_column='fn_filial_id', on_delete=django.db.models.deletion.RESTRICT, to='api.filial')),
                ('solicitacao_tipo', models.ForeignKey(db_column='fn_solicitacao_tipo_id', on_delete=django.db.models.deletion.RESTRICT, to='api.solicitacaotipo')),
            ],
            options={
                'db_table': 't_regras_aprovacao',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoSenhaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_column='fn_solicitacao_senha_chave', max_length=10, unique=True)),
                ('solicitacao_senha', models.ForeignKey(db_column='fn_solicitacao_senha_id', on_delete=django.db.models.deletion.RESTRICT, to='api.solicitacaosenha')),
                ('status', models.ForeignKey(db_column='fn_status_id', on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
            options={
                'db_table': 't_solicitacao_senha_chave',
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.ForeignKey(db_column='fn_status_id', on_delete=django.db.models.deletion.RESTRICT, to='api.status'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='fs_usuario_nome', max_length=150)),
                ('sobrenome', models.CharField(db_column='fs_usuario_sobrenome', max_length=150)),
                ('email', models.EmailField(db_column='fs_usuario_email', max_length=254, unique=True)),
                ('senha_hash', models.CharField(db_column='fs_usuario_senha_hash', max_length=255)),
                ('cargo', models.ForeignKey(db_column='fn_cargo_id', on_delete=django.db.models.deletion.RESTRICT, to='api.cargo')),
                ('filial', models.ForeignKey(db_column='fn_filial_id', on_delete=django.db.models.deletion.RESTRICT, to='api.filial')),
                ('setor', models.ForeignKey(db_column='fn_setor_id', on_delete=django.db.models.deletion.RESTRICT, to='api.setor')),
                ('status', models.ForeignKey(db_column='fn_status_id', on_delete=django.db.models.deletion.RESTRICT, to='api.status')),
            ],
            options={
                'db_table': 't_usuarios',
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario',
            field=models.ForeignKey(db_column='fn_usuario_id', on_delete=django.db.models.deletion.RESTRICT, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_aprovacao', models.IntegerField(db_column='fn_aprovacao_nivel')),
                ('solicitacao', models.ForeignKey(db_column='fn_solicitacao_id', on_delete=django.db.models.deletion.RESTRICT, to='api.solicitacao')),
                ('status', models.ForeignKey(db_column='fn_status_id', on_delete=django.db.models.deletion.RESTRICT, to='api.status')),
                ('usuario', models.ForeignKey(db_column='fn_usuario_id', on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
            options={
                'db_table': 't_aprovacoes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='fn_role_id', on_delete=django.db.models.deletion.RESTRICT, to='api.role')),
                ('status', models.ForeignKey(db_column='fn_status_id', on_delete=django.db.models.deletion.RESTRICT, to='api.status')),
                ('usuario', models.ForeignKey(db_column='fn_usuario_id', on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
            options={
                'db_table': 't_usuario_roles',
            },
        ),
    ]
