from .filial import urlpatterns as filial
from .usuario import urlpatterns as usuario
from .setor import urlpatterns as setor
from .status import urlpatterns as status
from .cargo import urlpatterns as cargo
from .role import urlpatterns as role
from .usuario_role import urlpatterns as usuario_role
from .tipo_senha import urlpatterns as tipo_senha
from .tipo_operacao_frete import urlpatterns as tipo_operacao_frete
from .solicitacao_tipo import urlpatterns as solicitacao_tipo
from .solicitacao import urlpatterns as solicitacao